StudentEnrollmentsPZ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("app.urls")),
    # path('accounts/profile', include("app.urls")),
    path("admin/", admin.site.urls),
]

app/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path

from app import views
from app.forms import LoginForm
from app.views import (
    IndexView,
    StudentsView,
    GroupsView,
    send_message,
    RegisterView,
    ProfileView,
    ProfileLogout,
    LoginView,
    ChatMain,
    ChatPrivate,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("/", IndexView.as_view(), name="default"),
    path("students", StudentsView.as_view(), name="students"),
    path("send_message", send_message, name="send_message"),
    path("groups", GroupsView.as_view(), name="groups"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", ProfileLogout.as_view(), name="logout"),
    path("register", RegisterView.as_view(), name="register"),
    path("chat_main", ChatMain.as_view(), name="chat_main"),
    path("chat_private", ChatPrivate.as_view(), name="chat_private"),
    path("group_report/", views.group_report, name="group_report"),
]

app/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models


class Grupy(models.Model):
    ID = models.AutoField(primary_key=True)
    Nazwa = models.CharField(max_length=32)

    def __str__(self):
        return str(self.Nazwa)


class Studenci(models.Model):
    ID_studenta = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    imie = models.CharField(max_length=50)
    nazwisko = models.CharField(max_length=50)
    mail = models.CharField(max_length=50, unique=False)
    ID_grupy = models.ForeignKey(
        Grupy, on_delete=models.CASCADE, related_name="id_grupy", null=True
    )

    def __str__(self):
        return f"{self.ID_studenta} [{self.ID_grupy}] {self.imie} {self.nazwisko}"


class Transfer(models.Model):
    ID_transfer = models.AutoField(primary_key=True)
    requester_student_ID = models.ForeignKey(
        Studenci, on_delete=models.CASCADE, related_name="requested_transfers"
    )
    exchanger_student_ID = models.ForeignKey(
        Studenci, on_delete=models.CASCADE, related_name="exchanged_transfers"
    )
    approved = models.BooleanField(default=None, null=True)

    def __str__(self):
        return f"{self.ID_transfer} ({self.requester_student_ID} - {self.exchanger_student_ID})"


class CzatOgolny(models.Model):
    ID_wiadomosci = models.AutoField(primary_key=True)
    tresc_wiadomosci = models.CharField(max_length=255, null=True)
    data_wiadomosci = models.DateField(null=True)
    ID_studenta = models.ForeignKey(Studenci, on_delete=models.CASCADE)


class CzatPrywatny(models.Model):
    ID_wiadomosci = models.AutoField(primary_key=True)
    tresc_wiadomosci = models.CharField(max_length=255, null=True)
    data_wiadomosci = models.DateField(null=True)
    ID_studenta_nadawcy = models.ForeignKey(
        Studenci, on_delete=models.CASCADE, related_name="nadawca"
    )
    ID_studenta_odbiorcy = models.ForeignKey(
        Studenci, on_delete=models.CASCADE, related_name="odbiorca"
    )


class Request(models.Model):
    sender = models.ForeignKey(
        Studenci, on_delete=models.CASCADE, related_name="sender_requests"
    )
    recipient = models.ForeignKey(
        Studenci, on_delete=models.CASCADE, related_name="recipient_requests"
    )
    status = models.CharField(max_length=50)

templates/app/change_group.html
<form method="post">
    {% csrf_token %}
    <select name="student_id">
        {% for student in students %}
            <option value="{{ student.id }}">{{ student.name }}</option>
        {% endfor %}
    </select>
    <select name="group_id">
        {% for group in groups %}
            <option value="{{ group.id }}">{{ group.name }}</option>
        {% endfor %}
    </select>
    <button type="submit">Change Group</button>
</form>

templates/app/change_password.html
<form method="post">
    {% csrf_token %}
    <input type="text" name="email" placeholder="Email">
    <input type="password" name="old_password" placeholder="Old Password">
    <input type="password" name="new_password" placeholder="New Password">
    <button type="submit">Change Password</button>
</form>

templates/app/chat.html
<div>
    <ul>
        {% for message in messages %}
            <li>{{ message.sender.name }}: {{ message.content }}</li>
        {% endfor %}
    </ul>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="content">
        <button type="submit">Send</button>
    </form>
</div>

templates/app/chat_main.html
{% extends 'base.html' %}
{% block content %}
<h2 style="text-align: center">Czat ogólny</h2>

    <div class="msg_history">
        {% for message in chat_messages %}
            {% if message.ID_studenta.user.id == request.user.id %}
             <div class="outgoing_msg">
                <div class="sent_msg">
                    <p>{{ message.tresc_wiadomosci }}</p>
                    <span class="time_date">{{message.data_wiadomosci}}</span></div>
            </div>

            {% else %}

                <div class="incoming_msg">
                <div class="incoming_msg_img"><img src="https://ptetutorials.com/images/user-profile.png" alt="sunil">
                </div>
                <div class="received_msg">
                    <b>{{ message.ID_studenta.imie }} {{ message.ID_studenta.nazwisko }}</b>
                    <div class="received_withd_msg">
                        <p>{{ message.tresc_wiadomosci }}</p>
                        <span class="time_date">{{message.data_wiadomosci}}</span></div>
                </div>
                </div>
            {% endif %}
        {% endfor %}

        </div>
<div class="wysylka">
     <p>&nbsp</p>
        <form method="POST">
            {% csrf_token %}
            {{ form_as_p }}
            <div class="input-group">
                {{ form.tresc_wiadomosci }}
                <input type="text" name="tresc_wiadomosci" class="form-control" id="exampleFormControlInput1">
                 <input type="hidden" name="sender_id" value="{{ user.id }}">
                <button type="submit" class="btn btn-primary">Wyślij</button>
            </div>
        </form>
        <p>{{ message }}</p>
    </div>
    </div>
{% endblock %}

templates/app/chat_private.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}

<div class="container">
<div class="row clearfix">
    <div class="col-lg-12">
        <div class="card chat-app">
            <div id="plist" class="people-list">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-search"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Search...">
                </div>
                <ul class="list-unstyled chat-list mt-2 mb-0">
                    <li class="clearfix">
                        <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="avatar">
                        <div class="about">
                            <div class="name">Vincent Porter</div>
                            <div class="status"> <i class="fa fa-circle offline"></i> left 7 mins ago </div>
                        </div>
                    </li>
                    <li class="clearfix active">
                        <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="avatar">
                        <div class="about">
                            <div class="name">Aiden Chavez</div>
                            <div class="status"> <i class="fa fa-circle online"></i> online </div>
                        </div>
                    </li>
                    <li class="clearfix">
                        <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="avatar">
                        <div class="about">
                            <div class="name">Mike Thomas</div>
                            <div class="status"> <i class="fa fa-circle online"></i> online </div>
                        </div>
                    </li>
                    <li class="clearfix">
                        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar">
                        <div class="about">
                            <div class="name">Christian Kelly</div>
                            <div class="status"> <i class="fa fa-circle offline"></i> left 10 hours ago </div>
                        </div>
                    </li>
                    <li class="clearfix">
                        <img src="https://bootdey.com/img/Content/avatar/avatar8.png" alt="avatar">
                        <div class="about">
                            <div class="name">Monica Ward</div>
                            <div class="status"> <i class="fa fa-circle online"></i> online </div>
                        </div>
                    </li>
                    <li class="clearfix">
                        <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="avatar">
                        <div class="about">
                            <div class="name">Dean Henry</div>
                            <div class="status"> <i class="fa fa-circle offline"></i> offline since Oct 28 </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="chat">
                <div class="chat-header clearfix">
                    <div class="row">
                        <div class="col-lg-6">
                            <a href="javascript:void(0);" data-toggle="modal" data-target="#view_info">
                                <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="avatar">
                            </a>
                            <div class="chat-about">
                                <h6 class="m-b-0">Aiden Chavez</h6>
                                <small>Last seen: 2 hours ago</small>
                            </div>
                        </div>
                        <div class="col-lg-6 hidden-sm text-right">
                            <a href="javascript:void(0);" class="btn btn-outline-secondary"><i class="fa fa-camera"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-primary"><i class="fa fa-image"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-info"><i class="fa fa-cogs"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-warning"><i class="fa fa-question"></i></a>
                        </div>
                    </div>
                </div>
                <div class="chat-history">
                    <ul class="m-b-0">
                        <li class="clearfix">
                            <div class="message-data text-right">
                                <span class="message-data-time">10:10 AM, Today</span>
                                <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar">
                            </div>
                            <div class="message other-message float-right"> Hi Aiden, how are you? How is the project coming along? </div>
                        </li>
                        <li class="clearfix">
                            <div class="message-data">
                                <span class="message-data-time">10:12 AM, Today</span>
                            </div>
                            <div class="message my-message">Are we meeting today?</div>
                        </li>
                        <li class="clearfix">
                            <div class="message-data">
                                <span class="message-data-time">10:15 AM, Today</span>
                            </div>
                            <div class="message my-message">Project has been already finished and I have results to show you.</div>
                        </li>
                    </ul>
                </div>
                <div class="chat-message clearfix">
                    <div class="input-group mb-0">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-send"></i></span>
                        </div>
                        <input type="text" class="form-control" placeholder="Enter text here...">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/app/confirm_action.html
<div>
    <p>Are you sure you want to perform this action?</p>
    <button>Yes</button>
    <button>No</button>
</div>

templates/app/empty.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/app/groups.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}
{% block content %}
<div class="row">
   <div class="col-md-9">
      <div class="wrapper">
         {% for group in groups %}
         <div class="item col-md-6">
            <div class="tablespace">
               <h2>Grupa {{ group.Nazwa }} ({{ group.id_grupy.count }}/{{ students_max.value }})</h2>
               {% if not user.is_authenticated or group.id_grupy.count >= students_max.value %}
               <button type="button" class="btn btn-primary disabled" disabled>Dołącz do grupy</button>
               {% elif group.id_grupy.count < students_min.value %}
               <button type="button" class="btn btn-primary disabled" disabled>Dołącz do grupy (za mało studentów)</button>
               {% else %}
                   <form method="POST">
                     {% csrf_token %}
                       <input type="hidden" name="group_id" value="{{ group.ID }}">
                       <button type="submit" class="btn btn-primary" name="transfer_form" value="join_to_group" data-toggle="modal" data-target="#transferModal{{ student.id }}">Dołącz do grupy</button>
                   </form>
               {% endif %}
               <table class="table table-striped">
                  <thead class="thead-dark">
                     <tr>
                        <th>ID</th>
                        <th>Imię</th>
                        <th>Nazwisko</th>
                        <th>Zamiana</th>
                     </tr>
                  </thead>
                  <tbody>
                     {% for student in group.id_grupy.all %}
                     <tr>
                        <td>{{ student.ID_studenta }}</td>
                        <td>{{ student.imie }}</td>
                        <td>{{ student.nazwisko }}</td>
                        <td>
                           <form method="post">
                              {% csrf_token %}
                              <input type="hidden" name="requester_student_ID" value="{{ user.id }}">
                              <input type="hidden" name="exchanger_student_ID" value="{{ student.user.id }}">
                              <button type="submit" class="btn btn-primary" name="transfer_form" value="transfer_form">Zamień</button>
                           </form>
                        </td>
                     </tr>
                     {% endfor %}
                  </tbody>
               </table>
            </div>
            {% if group.studenci_set.count < students_min.value %}
            <u>
               <p>Niepełna grupa!</p>
            </u>
            <br>
            <i>Brakuje {{ students_min.value|sub:group.studenci_set.count }} studentów do utworzenia
            grupy.</i>
            {% endif %}
         </div>
         {% endfor %}
      </div>
   <div class="col-md-12">
      <a href="{% url 'group_report' %}" class="btn btn-primary" role="button">Pobierz raport (PDF)</a>
   </div>
   </div>
   <h2>Czekające na akceptację</h2>
     <p><b>Grupa </b>{{ my_group_nr }}</p>
   <div class="col-md-3 msg_history2">
      <table class="table table-striped">
         <thead>
            <tr>
               <th>Wnioskujący</th>
               <th>___</th>
               <th>Zamiennik</th>
               <th>Wybór</th>
            </tr>
         </thead>
         <tbody>
            {% if transfers %}
            {% for transfer in transfers %}
            <tr>
               <td>{{ transfer.requester_student_ID.imie }} {{ transfer.requester_student_ID.nazwisko }}</td>
               <td><img class="icons" src="{% static 'icons/exchange.svg' %}" alt="exchange"/> </td>
               <td>{{ transfer.exchanger_student_ID.imie }} {{ transfer.exchanger_student_ID.nazwisko }}</td>
               <td>
                  <form method="POST" >
                     {% csrf_token %}
                     <input type="hidden" name="transfer_id" value="{{ transfer.ID_transfer }}">
                     <div class="btn-group" role="group" aria-label="Transfer actions">
                          {% if user.is_staff %}
                        <button type="submit" name="transfer_form" value="approve_form"><img class="icons" src="{% static 'icons/accept.png' %}" alt="accept"/></button>
                        <button type="button" name="transfer_form" value="approve_form" data-toggle="modal" data-target="#rejectModal{{ transfer.ID_transfer }}"><img class="icons" src="{% static 'icons/reject.png' %}" alt="accept"/></button>
                         {% else %}
                              <img class="icons" src="{% static 'icons/disabled.svg' %}" alt="accept"/>
                         {% endif %}
                     </div>
                     <div class="modal fade" id="rejectModal{{ transfer.ID_transfer }}" tabindex="-1" role="dialog" aria-labelledby="rejectModalLabel{{ transfer.ID_transfer }}" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                           <div class="modal-content">
                              <div class="modal-header">
                                 <h5 class="modal-title" id="rejectModalLabel{{ transfer.ID_transfer }}">Odrzucenie zamiany: {{ transfer.ID_transfer }}</h5>
                                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                 <span aria-hidden="true">&times;</span>
                                 </button>
                              </div>
                              <div class="modal-body">
                                 <p>Czy chcesz odrzucić ten transfer?</p>
                                 <button type="button" class="btn btn-secondary btn_exchange" data-dismiss="modal">Anuluj</button>
                                 <button type="submit" name="transfer_form" value="reject_form"  class="btn btn-danger btn_exchange">Odrzuć</button>
                              </div>
                           </div>
                        </div>
                     </div>
                  </form>
               </td>
            </tr>
            {% endfor %}
            {% else %}
            <p>Brak wniosków o zamianie.</p>
            {% endif %}
         </tbody>
      </table>
      <h3>Zatwierdzone</h3>
      <table class="table table-striped">
         <thead>
            <tr>
               <th>Wnioskujący</th>
               <th>Zamiennik</th>
               <th>Decyzja</th>
            </tr>
         </thead>
         <tbody>
            {% for transfer in transfer_approved %}
            <tr>
               <td>{{ transfer.requester_student_ID.imie }} {{ transfer.requester_student_ID.nazwisko }}</td>
               <td>{{ transfer.exchanger_student_ID.imie }} {{ transfer.exchanger_student_ID.nazwisko }}</td>
               {% if transfer.approved %}
               <td><img class="icons" src="{% static 'icons/accept.png'  %}" alt="accept"/></td>
               {% else %}
               <td><img class="icons" src="{% static 'icons/reject.png'  %}" alt="accept"/></td>
               {% endif %}
            </tr>
            {% endfor %}
         </tbody>
      </table>
   </div>
</div>
{% endblock %}

templates/app/grupy student.html
<head>
	<link rel="stylesheet" href="../CSS/style.css">
	<script src="../JS/skrypt.js"></script>
</head>

<body>
    <!-- navbar -->
    <div class="topnav">
        <a class="active" href="#home">System zarządzania studentami</a>
		<a href="">Grupy</a>
		<a href="">Czat</a>
        <div class="topnav-right">
            <button class="open-button" onclick="openForm()">Wyloguj</button>
        </div>
    </div>
	<div id="content">
		<div id="groups">
		<table id="grouptable">
		<tr>
			<th>
			<div class="grupa">
				<div class="col-md-12">
					<div class="col-md-4">
						<h2>Grupa 1</h2>
						<table class="table table-striped">
							<thead class="thead-dark">
							<tr>
								<th>ID</th>
								<th>Imię</th>
								<th>Nazwisko</th>
							</tr>
							</thead>
							<tbody>
								<tr>
									<td>162345</td>
									<td>Wojciech</td>
									<td>Nowakowski</td>
								</tr>
							</tbody>
						</table>

					</div>
				</div>
			</div>
			<div class="join"><button>zgłoś chęć dołączenia</button></div>
			</th>
			<th>
			<div class="grupa">
				<div class="col-md-12">
					<div class="col-md-4">
						<h2>Grupa 1</h2>
						<table class="table table-striped">
							<thead class="thead-dark">
							<tr>
								<th>ID</th>
								<th>Imię</th>
								<th>Nazwisko</th>
							</tr>
							</thead>
							<tbody>
								<tr>
									<td>162345</td>
									<td>Wojciech</td>
									<td>Nowakowski</td>
								</tr>
							</tbody>
						</table>

					</div>
				</div>
			</div>
			<div class="join"><button>zgłoś chęć dołączenia</button></div>
			</th>
			<th>
			<div class="grupa">
				<div class="col-md-12">
					<div class="col-md-4">
						<h2>Grupa 1</h2>
						<table class="table table-striped">
							<thead class="thead-dark">
							<tr>
								<th>ID</th>
								<th>Imię</th>
								<th>Nazwisko</th>
							</tr>
							</thead>
							<tbody>
								<tr>
									<td>162345</td>
									<td>Wojciech</td>
									<td>Nowakowski</td>
								</tr>
							</tbody>
						</table>

					</div>
				</div>
			</div>
			<div class="join"><button>zgłoś chęć dołączenia</button></div>
			</th>
			
			<th>
			<div class="grupa">
				<div class="col-md-12">
					<div class="col-md-4">
						<h2>Grupa 1</h2>
						<table class="table table-striped">
							<thead class="thead-dark">
							<tr>
								<th>ID</th>
								<th>Imię</th>
								<th>Nazwisko</th>
							</tr>
							</thead>
							<tbody>
								<tr>
									<td>162345</td>
									<td>Wojciech</td>
									<td>Nowakowski</td>
								</tr>
							</tbody>
						</table>

					</div>
				</div>
			</div>
			<div class="join"><button>zgłoś chęć dołączenia</button></div>
			</th>
			<th>
			<div class="grupa">
				<div class="col-md-12">
					<div class="col-md-4">
						<h2>Grupa 1</h2>
						<table class="table table-striped">
							<thead class="thead-dark">
							<tr>
								<th>ID</th>
								<th>Imię</th>
								<th>Nazwisko</th>
							</tr>
							</thead>
							<tbody>
								<tr>
									<td>162345</td>
									<td>Wojciech</td>
									<td>Nowakowski</td>
								</tr>
							</tbody>
						</table>

					</div>
				</div>
			</div>
			<div class="join"><button>zgłoś chęć dołączenia</button></div>
			</th>
			<th>
			<div class="grupa">
				<div class="col-md-12">
					<div class="col-md-4">
						<h2>Grupa 1</h2>
						<table class="table table-striped">
							<thead class="thead-dark">
							<tr>
								<th>ID</th>
								<th>Imię</th>
								<th>Nazwisko</th>
							</tr>
							</thead>
							<tbody>
								<tr>
									<td>162345</td>
									<td>Wojciech</td>
									<td>Nowakowski</td>
								</tr>
							</tbody>
						</table>

					</div>
				</div>
			</div>
			<div class="join"><button>zgłoś chęć dołączenia</button></div>
			</th>
			<th>
			<div class="grupa">
				<div class="col-md-12">
					<div class="col-md-4">
						<h2>Grupa 1</h2>
						<table class="table table-striped">
							<thead class="thead-dark">
							<tr>
								<th>ID</th>
								<th>Imię</th>
								<th>Nazwisko</th>
							</tr>
							</thead>
							<tbody>
								<tr>
									<td>162345</td>
									<td>Wojciech</td>
									<td>Nowakowski</td>
								</tr>
							</tbody>
						</table>

					</div>
				</div>
			</div>
			<div class="join"><button>zgłoś chęć dołączenia</button></div>
			</th>
			<th>
			<div class="grupa">
				<div class="col-md-12">
					<div class="col-md-4">
						<h2>Grupa 1</h2>
						<table class="table table-striped">
							<thead class="thead-dark">
							<tr>
								<th>ID</th>
								<th>Imię</th>
								<th>Nazwisko</th>
							</tr>
							</thead>
							<tbody>
								<tr>
									<td>162345</td>
									<td>Wojciech</td>
									<td>Nowakowski</td>
								</tr>
							</tbody>
						</table>

					</div>
				</div>
			</div>
			<div class="join"><button>zgłoś chęć dołączenia</button></div>
			</th>
		</tr>
		</table>
		</div>
		<div id="allchat">
			<div class="chattitle">Otwarte zgłoszenia</div>
			<div class="zgloszenia">
			<div class="zgloszenie">Maciej J <--> Julia W<br><button>Potwierdź</button><button>Odrzuć</button></div>
			<div class="zgloszenie">Norbert K. --> Grupa 1</div>
			<div class="zgloszenie">Norbert K. --> Grupa 1</div>
			<div class="zgloszenie">Norbert K. --> Grupa 1</div>
			<div class="zgloszenie">Norbert K. --> Grupa 1</div>
			<div class="zgloszenie">Norbert K. --> Grupa 1</div>
			<div class="zgloszenie">Norbert K. --> Grupa 1</div>
			<div class="zgloszenie">Norbert K. --> Grupa 1</div>
			<div class="zgloszenie">Norbert K. --> Grupa 1</div>
			<div class="zgloszenie">Norbert K. --> Grupa 1</div>
			<div class="zgloszenie">Norbert K. --> Grupa 1</div>
			</div>
		</div>
	</div>
</body>

templates/app/index.html
{% extends 'base.html' %}
{% block content %}

{% if request.user.is_staff %}
<h1>Lista studentów</h1>
<ul>
    {% for student in studenci %}
        <li>{{ student.imie }} {{ student.nazwisko }}</li>
    {% endfor %}
</ul>
{%endif%}
{% endblock %}

templates/app/notification.html
<ul>
    {% for notification in notifications %}
        <li>{{ notification }}</li>
    {% endfor %}
</ul>

templates/app/requests_list.html
<ul>
    {% for request in requests %}
        <li>{{ request.sender.name }} wants to switch to group {{ request.recipient.group.name }} <button>Accept</button> <button>Reject</button></li>
    {% endfor %}
</ul>

templates/app/students.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet"/>
    <link href="{% static 'CSS/students.css' %}" rel="stylesheet"/>
    <title>Document</title>
    <style>

    </style>
</head>
<body>
<div class="v1_12">
    <div class="v1_11">
        <div class="v1_3"></div>
        <div class="v1_7"></div>
        <div class="v1_9"></div>
        <span class="v1_6">Students</span>
        <span class="v1_8">Grupa 1</span>
            <ul>
                {% for student in studenci %}
                    <li>{{ student.imie }} {{ student.nazwisko }}</li>
                {% endfor %}
            </ul>
        <span class="v1_10">Grupa 2</span>
    </div>
</div>
<div class="d-flex flex-nowrap overflow-auto">
    <p>123</p>
    <p>123</p>
    <p>123</p>
    <p>123</p>
    <p>123</p>
</div>

</body>
</html>